version: "3.9"

services:
  db:
    image: mysql:8
    container_name: emi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: major_project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: emi-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./docker/Frontend
      dockerfile: Dockerfile
    container_name: emi-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
